tester_stage:
  stage: tester
  image: ubuntu:latest
  environment: Staging
  script:
  - cp -r * /tmp
  - apt-get update -qq && apt-get install -y -qq curl && apt-get install sshpass -y
  - export SSHPASS=$USER_PASS
  - sshpass -e ssh -p34722 root@localhost 'gunicorn -b 0.0.0.0:8000 --log-level debug api:app'
  - ./tmp/teste1.sh
  - pkill gunicor


