image: ubuntu:latest
stages:
  - build
  - test
  - staging

build:
  stage: build
  script:
    - echo "Iniciando Stage Testing:"
    - cp -R * /tmp
    - ls -ltr /tmp
    - chmod +x tester1.sh && chmod 777 tester1.sh
    - apt-get update -qq && apt-get install -y -qq curl && apt-get install sshpass -y 

teste:
  stage: build
  except:
    - master
  only:
    - homolog
  script:
    - echo "Iniciando Stage Testing:"
    - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p34722 root@192.168.1.114 "/var/www/html/desafio_devops/app/start_api.sh &"
    - ./tester2.sh
    - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p34722 root@192.168.1.114 "pkill gunicor"

teste2:
  stage: build
  except:
    - master
  only:
    - homolog
  script:
    - echo "Iniciando Stage Testing:"
    - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p34722 root@192.168.1.114 "/var/www/html/desafio_devops/app/start_api.sh &"
    - ./tester1.sh
    - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p34722 root@192.168.1.114 "pkill gunicor"

job_deploy:
  stage: staging
  script:
    - sshpass -p Acqwp2012 scp -o StrictHostKeyChecking=no -p34722 * /app
