image: ubuntu:latest
stages:
  - test

test:
  stage: test
  except:
    - master
  only:
    - homolog
  script:
    - echo "Iniciando Stage Testing:"
    - apt-get update -qq && apt-get install -y -qq curl && apt-get install sshpass -y 
    - cp -R * /tmp
    - sshpass -p Acqwp2012 ssh -p34722 root@25.1.14.127 'cd /app/ && gunicorn -b 0.0.0.0:8000 --log-level debug api:app && '
    - ./tmp/teste1.sh
    - pkill gunicor
