image: ubuntu:latest
stages:
  - test
  - staging

Teste_api:
  stage: test
  script:
    - cp -R * /tmp
    - ls -ltr /tmp
    - chmod +x tester1.sh && chmod 777 tester1.sh && chmod +x tester2.sh && chmod 777 tester2.sh
    - apt-get update -qq && apt-get install -y -qq curl && apt-get install sshpass -y 
    - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p34722 root@192.168.1.114 "/app/start_api.sh &"
    - sleep 3
    - echo "Iniciando Stage 1 Testing:"
    - ./tester1.sh
    - echo "Iniciando Stage 2 Testing:"
    - ./tester2.sh
    - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p34722 root@192.168.1.114 "pkill gunicor"

job_deploy:
  stage: staging
  needs: ["Teste_api"]
  script:
    - apt-get update -y && apt-get install sshpass -y
    - sshpass -p Acqwp2012 scp -o stricthostkeychecking=no -P 35722 -r * root@192.168.1.114:/app/
    - sshpass -p Acqwp2012 ssh -o StrictHostKeyChecking=no -p35722 root@192.168.1.114 "/app/start_api.sh &"

